# Generated by Django 4.2.7 on 2026-03-01 11:09

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='video',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='assignment_videos'),
        ),
        migrations.AddField(
            model_name='course',
            name='cover_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='course_images'),
        ),
        migrations.AddField(
            model_name='course',
            name='intro_video',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='course_videos'),
        ),
    ]
